baseURL = "/"
languageCode = "en-us"
title = "Samarth's Website"
theme = "hugo-xmin"
enableRobotsTXT = true
footnotereturnlinkcontents = "↩"

[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 2
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3
[[menu.main]]
name = "RSS"
url = "/index.xml"
weight = 4

[params]
footer = "&copy; Samarth Kishor 2024 | [Github](https://github.com/samarthkishor)"

[params.source]
org_dir = "content-org"
md_dir = "content"

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Samarth Kishor" # Author full name
authorEmail = "samarth@samarth.me" # Author email

[params.assets]
customCSS = ["css/styles.css"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

[markup.goldmark.renderer]
unsafe = true
